version: '3'

services:
  www:
      container_name: web
      build: .
      restart: always
      ports:
        - '9002:80'
      volumes:
        #- ./www:/var/www/html
        #- .:/var/www/html
        - ./src:/var/www/html
        - ./vendor:/var/www/vendor
        
      networks:
        - default
      depends_on:
        - db
  db:
      container_name: database
      image: mysql:5.7
      restart: always
      ports:
          - '3306:3306'
      environment:
        MYSQL_DATABASE: poke
        MYSQL_USER: ANDREY
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 12345
        #MYSQL_ALLOW_EMPTY_PASSWORD:
      volumes:
          - db_data:/var/lib/mysql
      networks:
          - default
volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge